name: build-psp

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspdev:latest   # готовый образ с psp-gcc и SDK
    steps:
      - uses: actions/checkout@v4

      - name: Build EBOOT.PBP
        run: |
          make clean
          make
          mkdir -p out
          cp EBOOT.PBP out/EBOOT.PBP

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EBOOT.PBP
          path: out/EBOOT.PBP










